language: python
dist: trusty

python:
  - "3.7-dev"

cache: pip

env:
  global:
    - PACKAGENAME='MyScripts'

before install:
  #  - pip install -r requirements.txt
  - pip install pandas
  - pip install folium
  - pip install openpyxl
  - pip install xlrd
  - pip install requests

install:
  - python setup.py install

addons:
  sonarcloud:
    organization: "kwbln-github" # the key of the org you chose at step #3
  #    token:
  #      secure: "" # encrypted value of your token


script:
  - sonar-scanner
  - python MyScripts/DataDemo.py
