language: python
dist: trusty

python:
  - '3.7-dev'

cache: pip

env:
  global:
    - PACKAGENAME='petproject'

addons:
  sonarcloud:
    organization: 'kwbln-github'

before_install:
  - pip install -r requirements.txt

install:
  - python setup.py sdist
  - python setup.py install

before_script:
  - sonar-scanner

script:
  - python runner
