language: python
dist: trusty

python:
  - '3.7-dev'

cache: pip

env:
  global:
    - PACKAGENAME='MyScripts'

addons:
  sonarcloud:
    organization: 'kwbln-github' # the key of the org you chose at step #3
  #    token:
  #      secure: "" # encrypted value of your token

before_install:
  - pip install -r requirements.txt

install:
  - python setup.py -q install

before_script:
  - sonar-scanner

script:
  - sonar-scanner
  - python package/DataDemo.py
