@startuml

package "Athlet" {

    [Model] <- [Controller]
    [View] <- [Controller]

    package "Model" {
        [Data]
        [ColorScheme]
    }

    package "View" {
        [Userprofile]
        [Forecast]
        [History]
        [Heatmap]
    }

}

@enduml